name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x     

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x      
  
    - name: Setup Go environment
      uses: actions/setup-go@v2.2.0
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Check Env
      run: env
    
    - name: Set Env
      run: echo "$env:XYZ=AAAA"
      
    - name: Simple set environment variables
      # You may pin to the exact commit or the version.
      # uses: trevorlloydelliott/set-environment-variables@6e117811abc56323c2d24209039f6f49ffa7d265
      uses: trevorlloydelliott/set-environment-variables@v1.0.0
      with:
        DotNetCoreDirPathNet6: 'C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App\6.*\'
      
    - name: Check Env2
      run: env
    
    #
    # Someday I will figure this out, but not today.
    # - name: check vars
    #  run: echo "$env:GITHUB_WORKSPACE"
    # - name: App Settings Variable Substitution
    #  uses: microsoft/variable-substitution@v1
    #  with:
    #    files: '$env:GITHUB_WORKSPACE\src\PowerUp.Tests\appsettings.json'
    #  env:
    #    DotNetCoreDirPathNet6: 'C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App\'
    #    DotNetCoreDirPathDefault: 'C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App\'
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test
